export const AMENITY_OPTIONS = [
  "Parking",
  "Wifi",
  "Printer",
  "Water",
  "Chairs and Desks",
  "Separate Washroom",
  "Pantry",
  "Meeting Room",
  "Conference Room",
  "Air Conditioning",
  "Charging",
  "Power Backup",
  "Coffee",
  "Tea",
  "Phone Booth",
  "Reception",
  "Fire Extinguisher",
  "Security Personnel",
  "First Aid Kit",
  "Lift",
  "CCTV",
  "High Speed Internet",
];